name: visual_analytics
channels:
  - conda-forge
  - pytorch
  - fastai
dependencies:
  - python=3.7
  - pip
  - cuda100
#  - fastprogress
#  - fastai=1.0.58
#  - jupyter
#  - notebook
#  - setuptools
  - pip:
#      - pytest
      - nvidia-ml-py3
      - wordcloud
#      - dataclasses
#      - numpy
      - pandas
#      - pyyaml
#      - opencv-contrib-python
#      - requests
      - sklearn
#      - cython
##      - gym[box2d, atari]
#      - easydict
      - matplotlib
      - jupyter_console
##      - moviepy
##      - pygifsicle
      - jupyterlab
#      - nbdev
      - kaggle
      - jupyter
      - jupyterthemes